version: '3.1'
services:
    database:
        container_name: MariaDB
        restart: on-failure
        build:
            context: ./database
            dockerfile: Dockerfile
        network_mode: "host"
