version: '3.1'
services:
    database:
        container_name: MariaDB
        restart: always
        build:
            context: ./database
            dockerfile: Dockerfile
        network_mode: "host"
        ports :
            - "{MY_DATABASE_PORT}:3306"
